name_maximum: 50
email_maximun: 255
pass_minimun: 6
img_size: 80
gra_size: 50
user_per_page: 7
microposts_per_page: 3
time_zone: "Asia/Ho_Chi_Minh"
u_host: "localhost:3000"
hour_expired: 2
title_max: 255
content_max: 100000
picture_size_max: 5
hozi_max: 400
vert_max: 400
avatar_size: 50
image_type: "image/jpeg,image/gif,image/png"
users_per_page: 20
comment_per_page: 8
entries_per_home_page: 10
